# Generated by Django 5.1.2 on 2024-11-06 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=255)),
                ('emp_mail', models.EmailField(max_length=50, unique=True)),
                ('designation', models.CharField(max_length=50)),
            ],
        ),
    ]
